# Generated by Django 3.1.7 on 2021-03-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Start_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
